language: rust
rust:
  - stable
  - beta

os:
  - linux
  - osx

before_script:
  - rustup component add clippy
script:
  - cargo clippy
  - cargo clippy -- -D warnings
  - cargo build --all --all-targets
  - cargo test --all
